services:
  image-editor:
    image: sdonis/image-editor-1image:0.0.4
    build: .
    ports:
      - "9093:9093"
    environment:
      - COMFYUI_ADDRESS=<youriphere>:8188
    volumes:
      - ./outputs:/app/outputs
    restart: unless-stopped
